stages:
    - test
    - build

test:
    stage: test
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    image: circleci/php:7.3.9
    script:
        - composer install
        - vendor/bin/phpunit --coverage-text --colors=never --configuration phpunit.xml
    cache:
        paths:
            - vendor

build:
    stage: build
    image: circleci/php:7.3.9
    artifacts:
        name: cachebust-assets
        expire_in: 12 mos
        paths:
            - src/
            - vendor/
            - cachebust-assets.php
            - LICENSE
            - README.md
    script:
        # install prod dependencies
        - composer install --no-dev --optimize-autoloader
        # set version number in plugin meta
        - 'sed -i "s|Version: GIT|Version: $CI_COMMIT_REF_NAME|" cachebust-assets.php'
    cache:
        paths:
            - vendor
    only:
        - tags