stages:
    - test
    - build

image: circleci/php:7.3.9

cache:
    key: "$CI_JOB_NAME"
    paths:
        - vendor

test:
    stage: test
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    script: |
        composer install
        vendor/bin/phpunit --coverage-text --colors=never --configuration phpunit.xml

build:
    stage: build
    artifacts:
        name: release
        expire_in: 12 mos
        paths:
            - "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}.zip"
    script: |
        # install prod dependencies
        composer install --no-dev --optimize-autoloader
        # set version number in plugin meta
        sed -i "s|Version: GIT|Version: $CI_COMMIT_REF_NAME|" cachebust-assets.php
        zip "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" -r -9 *.php LICENSE src vendor
    only:
        - tags