before_script:
    # update and install needed packages
    - apt-get update -yqq
    - apt-get install -yqq wget git
    # install xdebug
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    # install composer
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') !== file_get_contents('installer.sig')) { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"

stages:
    - test
    - build

test:
    stage: test
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    image: php:7.2
    script:
        - php composer.phar install
        - vendor/bin/phpunit --coverage-text --colors=never --configuration phpunit.xml

build:
    stage: build
    image: php:7.2
    artifacts:
        name: cachebust-assets-$CI_COMMIT_REF_NAME
        expire_in: 12 mos
        paths:
            - src/
            - vendor/
            - cachebust-assets.php
            - LICENSE
            - README.md
    script:
        # install prod dependencies
        - php composer.phar install --no-dev --optimize-autoloader
    only:
        - tags